version: '3.3'

services:
  service-discovery:
    image: application/discovery-micro:naive
    build:
      context: discovery-micro/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    environment:
      SERVER_PORT: 8080
    ports:
      - "8761:8080"

  service-math:
    image: application/math-micro:naive
    build:
      context: math-micro/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      SERVER_PORT: 8080
      DISCOVERY_URL: http://service-discovery:8080/eureka/

  service-history:
    image: application/history-micro:naive
    build:
      context: history-micro/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      SERVER_PORT: 8080
      DISCOVERY_URL: http://service-discovery:8080/eureka/
    ports:
      - "8082:8080"

  service-exam:
    image: application/exam-micro:naive
    build:
      context: exam-micro/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      service-discovery:
        condition: service_healthy
    environment:
      SERVER_PORT: 8080
      DISCOVERY_URL: http://service-discovery:8080/eureka/
    ports:
      - "8081:8080"